version: "3.8"
services:
  db:
    image: postgres
    container_name: workout_app
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root